name: play
description: "EchoPlay is a Flutter application that allows users to download audio from YouTube links and play them directly within the app. It supports background audio playback, sharing intent for media, persistent downloads using Hive, and offline media management."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  youtube_explode_dart: ^2.3.10
  just_audio_background: ^0.0.1-beta.15
  just_audio: ^0.9.46
  path_provider:
  cached_network_image:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  progress_indicators: ^1.0.0
  receive_sharing_intent:
    git:
      url: https://github.com/KasemJaffer/receive_sharing_intent
      ref: 2cea396843cd3ab1b5ec4334be4233864637874e
  get:



dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
